

export const trending = [
    {
        "id": "00001",
        "name": "God Of War",
        "img": "./assets/games/game-1.webp",
        "price": "30",
        "oldPrice": "40",
        "qty": 1,
        "category": "Playstation",
        "status": true,

    },
    {
        "id": "00002",
        "name": "Sid Meier's Civilization VI",
        "img": "./assets/games/game-2.webp",
        "price": "20",
        "oldPrice": "25",
        "qty": 1,
        "category": "Xbox",
        "status": true,
    },
    {
        "id": "00003",
        "name": "Borderlands 2",
        "img": "./assets/games/game-3.webp",
        "price": "16",
        "oldPrice": "20",
        "qty": 1,
        "category": "Xbox",
        "status": false,
    },
    {
        "id": "00004",
        "name": "Ready Or Not",
        "img": "./assets/games/game-4.webp",
        "price": "10",
        "oldPrice": "15",
        "qty": 1,
        "category": "Playstation",
        "status": true,
    },
    {
        "id": "00005",
        "name": "Farming Simulator",
        "img": "./assets/games/game-5.webp",
        "price": "6",
        "oldPrice": "12",
        "qty": 1,
        "category": "Playstation",
        "status": false,
    },
    {
        "id": "00006",
        "name": "Lego Star Wars",
        "img": "./assets/games/game-6.webp",
        "price": "8",
        "oldPrice": "16",
        "qty": 1,
        "category": "Xbox",
        "status": false,
    },
    {
        "id": "00007",
        "name": "Fifa 22",
        "img": "./assets/games/game-7.webp",
        "price": "30",
        "oldPrice": "50",
        "qty": 1,
        "category": "Xbox",
        "status": true,
    },
    {
        "id": "00008",
        "name": "Dead By Dayight",
        "img": "./assets/games/game-8.webp",
        "price": "6",
        "oldPrice": "16",
        "qty": 1,
        "category": "Playstation",
        "status": true,
    },
    {
        "id": "00009",
        "name": "7 Days To Die",
        "img": "./assets/games/game-9.webp",
        "price": "5",
        "oldPrice": "14",
        "qty": 1,
        "category": "Playstation",
        "status": false,
    },
    {
        "id": "000010",
        "name": "The Walking Dead",
        "img": "./assets/games/game-10.webp",
        "price": "4",
        "oldPrice": "10",
        "qty": 1,
        "category": "Xbox",
        "status": true,
    },
    {
        "id": "000011",
        "name": "Dark Souls II",
        "img": "./assets/games/game-11.webp",
        "price": "10",
        "oldPrice": "22",
        "qty": 1,
        "category": "Playstation",
        "status": true,
    },
    {
        "id": "000012",
        "name": "Grand Theft Auto V",
        "img": "./assets/games/game-12.webp",
        "price": "33",
        "oldPrice": "46",
        "qty": 1,
        "category": "Playstation",
        "status": true,
    },
];

export const Users = [
    {
        id: 1,
        lastName: 'Snow',
        firstName: 'Jon',
        age: 35,
        img: "../assets/person/1.jpeg",
        online: true,
        phone: "+123456789",
        adress: "Rocky Hill, Connecticut(CT), 06067",
        chart : [{ name: 'January', total: 1500}, { name: 'March', total: 2000}, { name: 'May', total: 3000}]
    },
    {
        id: 2,
        lastName: 'Lannister',
        firstName: 'Cersei',
        age: 42,
        img: "../assets/person/2.jpeg",
        online: false,
        phone: "+123456789",
        adress: "Spencer, Tennessee(TN), 38585",
        chart : [{ name: 'January', total: 5000}, { name: 'March', total: 4000}, { name: 'May', total: 3000}]
    },
    {
        id: 3,
        lastName: 'Lannister',
        firstName: 'Jaime',
        age: 45,
        img: "../assets/person/3.jpeg",
        online: true,
        phone: "+123456789",
        adress: "Philadelphia, Pennsylvania(PA), 19104",
        chart : [{ name: 'January', total: 2000}, { name: 'March', total: 3000}, { name: 'May', total: 3000}]
    },
    {
        id: 4,
        lastName: 'Stark',
        firstName: 'Arya',
        age: 16,
        img: "../assets/person/4.jpeg",
        online: true,
        phone: "+123456789",
        adress: "Mahopac, New York(NY), 10541",
        chart : [{ name: 'January', total: 1500}, { name: 'March', total: 2000}, { name: 'May', total: 3000}]
    },
    {
        id: 5,
        lastName: 'Targaryen',
        firstName: 'Daenerys',
        age: 20,
        img: "../assets/person/5.jpeg",
        online: false,
        phone: "+123456789",
        adress: "Marion, Iowa(IA), 52302",
        chart : [{ name: 'January', total: 2000}, { name: 'March', total: 2000}, { name: 'May', total: 3000}]
    },
    {
        id: 6,
        lastName: 'Shirley',
        firstName: "Beauchamp",
        age: 40,
        img: "../assets/person/6.jpeg",
        online: false,
        phone: "+123456789",
        adress: "Rocky Hill, Connecticut(CT), 06067",
        chart : [{ name: 'January', total: 1500}, { name: 'March', total: 2000}, { name: 'May', total: 3000}]
    },
    {
        id: 7,
        lastName: 'Clifford',
        firstName: 'Ferrara',
        age: 44,
        img: "../assets/person/7.jpeg",
        online: false,
        phone: "+123456789",
        adress: "Mahopac, New York(NY), 10541",
        chart : [{ name: 'January', total: 8000}, { name: 'March', total: 4000}, { name: 'May', total: 2000}]
    },
    {
        id: 8,
        lastName: 'Frances',
        firstName: 'Rossini',
        age: 36,
        img: "../assets/person/8.jpeg",
        online: true,
        phone: "+123456789",
        adress: "Mahopac, New York(NY), 10541",
        chart : [{ name: 'January', total: 8000}, { name: 'March', total: 5000}, { name: 'May', total: 7000}]
    },
    {
        id: 9,
        lastName: 'Roxie',
        firstName: 'Harvey',
        age: 65,
        img: "../assets/person/9.jpeg",
        online: false,
        phone: "+123456789",
        adress: "Marion, Iowa(IA), 52302",
        chart : [{ name: 'January', total: 1500}, { name: 'March', total: 2000}, { name: 'May', total: 300}]
    },
    {
        id: 10,
        lastName: 'Safak',
        firstName: 'Kocaoglu',
        age: 25,
        img: "../assets/person/10.jpeg",
        online: true,
        phone: "+123456789",
        adress: "Warrenton, Virginia(VA), 20187",
        chart : [{ name: 'January', total: 500}, { name: 'March', total: 600}, { name: 'May', total: 700}]
    },
];
